nelmio_api_doc:
    documentation:
        info:
            title: Company Management API
            description: All information related to the features of the Company Management API
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
